# Generated by Django 5.2.5 on 2026-05-11 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hu', models.CharField(max_length=200, verbose_name='Cím (magyar)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cím (angol)')),
                ('description_hu', models.TextField(verbose_name='Leírás (magyar)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Leírás (angol)')),
                ('level', models.CharField(choices=[('beginner', 'Kezdő'), ('advanced', 'Haladó'), ('all', 'Minden szint')], default='all', max_length=20, verbose_name='Szint')),
                ('duration', models.CharField(help_text='Pl. 8 alkalom', max_length=100, verbose_name='Időtartam')),
                ('price', models.CharField(help_text='Pl. 35 000 Ft', max_length=100, verbose_name='Ár')),
                ('icon', models.CharField(blank=True, default='🎨', verbose_name='Ikon (emoji)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Tanfolyam',
                'verbose_name_plural': 'Tanfolyamok',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hu', models.CharField(max_length=200, verbose_name='Cím (magyar)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cím (angol)')),
                ('content_hu', models.TextField(verbose_name='Tartalom (magyar)')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Tartalom (angol)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Képfájl')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Dátum')),
            ],
            options={
                'verbose_name_plural': 'Hírek',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hu', models.CharField(max_length=200, verbose_name='Cím (magyar)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cím (angol)')),
                ('description_hu', models.TextField(verbose_name='Leírás (magyar)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Leírás (angol)')),
                ('technique', models.CharField(choices=[('watercolor', 'Akvarell'), ('acrylic', 'Akril'), ('oil', 'Olajfestmény'), ('pencil', 'Ceruza munka')], max_length=20, verbose_name='Technika')),
                ('image', models.ImageField(upload_to='paintings/', verbose_name='Képfájl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hu', models.CharField(max_length=200, verbose_name='Cím (magyar)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cím (angol)')),
                ('description_hu', models.TextField(blank=True, null=True, verbose_name='Leírás (magyar)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Leírás (angol)')),
                ('video_file', models.FileField(help_text='MP4 formátum ajánlott', upload_to='videos/', verbose_name='Videófájl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltve')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Videó',
                'verbose_name_plural': 'Videók',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Kép')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Képaláírás')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.news', verbose_name='Hír')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
