# Generated by Django 5.2.5 on 2026-04-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.CharField(blank=True, default='🎨', verbose_name='Ikon (emoji)'),
        ),
    ]
