# Generated by Django 5.2.5 on 2026-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hu', models.CharField(max_length=200, verbose_name='Cím (magyar)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cím (angol)')),
                ('description_hu', models.TextField(blank=True, null=True, verbose_name='Leírás (magyar)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Leírás (angol)')),
                ('video_file', models.FileField(help_text='MP4 formátum ajánlott', upload_to='videos/', verbose_name='Videófájl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltve')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Videó',
                'verbose_name_plural': 'Videók',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
