# Generated by Django 5.2.5 on 2025-10-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_news_alter_painting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Kép')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Képaláírás')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.news', verbose_name='Hír')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
