# Generated by Django 5.2.4 on 2025-08-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('description', models.TextField(verbose_name='Leírás')),
                ('technique', models.CharField(choices=[('watercolor', 'Akvarell'), ('acrylic', 'Akril'), ('oil', 'Olajfestmény'), ('pencil', 'Ceruza munka')], max_length=20, verbose_name='Technika')),
                ('image', models.ImageField(upload_to='paintings/', verbose_name='Képfájl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Festmény',
                'verbose_name_plural': 'Festmények',
                'ordering': ['-created_at'],
            },
        ),
    ]
